# Generated by Django 4.1.3 on 2022-11-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timereport',
            old_name='task_id',
            new_name='task',
        ),
    ]
