# Generated by Django 4.1.3 on 2022-12-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_alter_reportsummary_user_alter_task_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='auth_user',
        ),
    ]
