# Generated by Django 4.1.3 on 2022-11-29 21:53

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('custom_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_spent', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reported_for', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REPORTED', 'Reported'), ('PROCESSED', 'Processed'), ('DELETED', 'Deleted')], default='NEW', max_length=50)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.task')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('minutes_sum', models.PositiveIntegerField()),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='NEW', max_length=50)),
                ('time_reports', models.ManyToManyField(to='taxes.timereport')),
            ],
        ),
    ]
